# Generated by Django 4.1 on 2022-08-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loss_comunication',
            name='id',
        ),
        migrations.AlterField(
            model_name='loss_comunication',
            name='cpf_produtor',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
