# Generated by Django 4.1 on 2022-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_remove_loss_comunication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss_comunication',
            name='evento_ocorrido_produtor',
            field=models.CharField(choices=[('1', 'CHUVA EXCESSIVA'), ('2', 'GEADA'), ('3', 'GRANIZO'), ('4', 'SECA'), ('5', 'VENDAVAL'), ('6', 'RAIO')], default=None, max_length=1),
        ),
    ]
