# Generated by Django 4.1 on 2022-08-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_alter_loss_comunication_evento_ocorrido_produtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss_comunication',
            name='evento_ocorrido_produtor',
            field=models.CharField(choices=[('CHUVA EXCESSIVA', 'CHUVA EXCESSIVA'), ('GEADA', 'GEADA'), ('GRANIZO', 'GRANIZO'), ('SECA', 'SECA'), ('VENDAVAL', 'VENDAVAL'), ('RAIO', 'RAIO')], default=None, max_length=75),
        ),
    ]
