# Generated by Django 4.1 on 2022-08-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_alter_loss_comunication_evento_ocorrido_produtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss_comunication',
            name='data_colheita_produtor',
            field=models.CharField(max_length=11),
        ),
    ]
