# Generated by Django 4.1 on 2022-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loss_comunication',
            fields=[
                ('nome_produtor', models.CharField(max_length=75)),
                ('email_produtor', models.EmailField(max_length=254)),
                ('cpf_produtor', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('latitude_produtor', models.CharField(max_length=200)),
                ('longitude_produtor', models.CharField(max_length=200)),
                ('tipo_lavoura_produtor', models.CharField(max_length=75)),
                ('data_colheita_produtor', models.CharField(max_length=11)),
                ('evento_ocorrido_produtor', models.CharField(choices=[('CHUVA EXCESSIVA', 'CHUVA EXCESSIVA'), ('GEADA', 'GEADA'), ('GRANIZO', 'GRANIZO'), ('SECA', 'SECA'), ('VENDAVAL', 'VENDAVAL'), ('RAIO', 'RAIO')], default=None, max_length=75)),
            ],
        ),
    ]
